name: Commit build

on:
  push:
    branches:
      - master

jobs:
  android-build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull Latest Changes
        run: git pull origin master

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6

      - name: Get Dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: purevideo-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  # ios-build:
  #   name: Build iOS IPA
  #   runs-on: macos-latest

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Pull Latest Changes
  #       run: git pull origin master

  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: 3.32.6

  #     - name: Get Dependencies
  #       run: flutter pub get

  #     - name: Build iOS IPA
  #       run: flutter build ios --release --no-codesign

  #     - name: Create IPA File
  #       run: |
  #         mkdir -p Payload
  #         mv build/ios/iphoneos/Runner.app Payload/
  #         zip -qq -r -9 purevideo-release.ipa Payload

  #     - name: Upload IPA Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: purevideo-release.ipa
  #         path: purevideo-release.ipa
